### ISSUE TITLE
Release cycle - Autoupdate

### ISSUE THREAD

**Issue by jlpedrosa** [mkilchhofer/unifi-chart#9]
Hi!

Thanks for your work! I was planning to use it, I wanted to understand what is your release cadence and if you plan to have automatic updates for the chart for the container images. Renovate is working fine for me for chart versions, but I'm not sure for image tags, I was wondering if you'd be interested on doing automatic chart updates.

Thanks!

**Comment by mkilchhofer** [comment]
Hi @jlpedrosa 

Sorry for the late response. I introduced Renovate bot a few minutes ago.
Does that answer your question? ;) 

Until today I updated the chart manually as soon as I wanted to update my unifi contoller instance in my homelab.

**Comment by CompPhy** [comment]
It looks like you have an issue with your renovate setup.  See PR #28.

Command failed: ./scripts/renovate-bump-version.sh unifi
/bin/sh: 1: ./scripts/renovate-bump-version.sh: not found

Any chance you can get this fixed relatively soon?  You have one of the better unifi setups recently and I would like to get the latest version of the upstream container.  It contains a bug fix for a cert issue I reported last week.  Most specifically around using cert-manager configuration in kubernetes.

**Comment by mkilchhofer** [comment]
Closed with https://github.com/mkilchhofer/unifi-chart/pull/10
